# Generated by Django 3.1 on 2022-01-06 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spsapp', '0002_auto_20220106_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='game',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
