# Generated by Django 3.1 on 2022-01-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spsapp', '0003_auto_20220106_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='score',
        ),
        migrations.AddField(
            model_name='result',
            name='bot_move',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='result',
            name='user_move',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
